<?php

use Fisharebest\Webtrees\Http\RequestHandlers\RegisterAction;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Fisharebest\Webtrees\View;

/**
 * @var string    $captcha
 * @var string    $comments
 * @var string    $email
 * @var string    $realname
 * @var bool      $show_caution
 * @var string    $title
 * @var Tree|null $tree
 * @var string    $username
 */
?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<?php if ($show_caution) : ?>
    <div class="wt-register-caution">
        <?= I18N::translate('<div class="largeError">Notice:</div><div class="error">By completing and submitting this form, you agree:<ul><li>to protect the privacy of living individuals listed on our site;</li><li>and in the text box below, to explain to whom you are related, or to provide us with information on someone who should be listed on our website.</li></ul></div>') ?>
    </div>
<?php endif ?>

<form method="post" action="<?= e(route(RegisterAction::class, ['tree' => $tree instanceof Tree ? $tree->name() : null])) ?>" autocomplete="off" class="wt-page-options wt-page-options-register">
    <?= csrf_field() ?>
    <?= $captcha ?>

    <!-- Nom de famille -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="realname">
            <?= I18N::translate('Nom de famille') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="realname" name="realname" required="required" maxlength="64" value="<?= e($realname) ?>" autocomplete="name">
            <p class="small text-muted">
                <?= I18N::translate('Ceci est votre nom de famille, tel que vous aimeriez le voir à l’écran.') ?>
            </p>
        </div>
    </div>

    <!-- Prénom usuel-->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="givenname">
            <?= I18N::translate('Prénom') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="givenname" name="givenname" required="required" maxlength="32" value="<?= e($givenname) ?>" autocomplete="givenname">
            <p class="small text-muted">
                <?= I18N::translate('Ceci est votre vrai prénom, tel que vous aimeriez le voir à l’écran.') ?>
            </p>
        </div>
    </div>

    <!-- Prénoms d'état civil -->

    <!-- Email address -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="email">
            <?= I18N::translate('Email address') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="email" id="email" name="email" required="required" maxlength="64" value="<?= e($email) ?>" autocomplete="email">
            <p class="small text-muted">
                <?= I18N::translate('This email address will be used to send password reminders, website notifications, and messages from other family members who are registered on the website.') ?>
            </p>
        </div>
    </div>

    <!-- Pseudo -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="username">
            <?= I18N::translate('Username') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="username" name="username" required="required" maxlength="32" value="<?= e($username) ?>" autocomplete="username">
            <p class="small text-muted">
                <?= I18N::translate('Usernames are case-insensitive and ignore accented letters, so that “chloe”, “chloë”, and “Chloe” are considered to be the same.') ?>
            </p>
        </div>
    </div>


    <!-- Date de naissance -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="birthdate">
            <?= I18N::translate('Date de naissance') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="date" id="birthdate" name="birthdate" required="required" maxlength="32" value="<?= e($birthdate) ?>" autocomplete="birthdate">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez indiquer votre date de naissance') ?>
            </p>
        </div>
    </div>

    <!-- Pays de naissance -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="birthcountry">
            <?= I18N::translate('Pays de naissance') ?>
        </label>

        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="birthcountry" name="birthcountry" required="required" maxlength="32" value="<?= e($birthcountry) ?>" autocomplete="birthcountry">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez indiquer votre pays de naissance.') ?>
            </p>
        </div>
    </div>

    <!-- Région de naissance -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="birthregion">
            <?= I18N::translate('Région de naissance') ?>
        </label>

        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="birthregion" name="birthregion" required="required" maxlength="32" value="<?= e($birthregion) ?>" autocomplete="birthregion">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez indiquer votre région de naissance.') ?>
            </p>
        </div>
    </div>

    <!-- Département de naissance -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="birthdepartment">
            <?= I18N::translate('Département de naissance') ?>
        </label>

        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="text" id="birthdepartment" name="birthdepartment" required="required" maxlength="32" value="<?= e($birthdepartment) ?>" autocomplete="birthdepartment">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez indiquer votre département de naissance.') ?>
            </p>
        </div>
    </div>

    <!-- Ville de naissance -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="birthplace">
            <?= I18N::translate('Ville de naissance') ?>
        </label>

        <div class="col-sm-5 wt-page-options-value">
            <input class="form-control" type="text" id="birthplace" name="birthplace" required="required" maxlength="32" value="<?= e($birthplace) ?>" autocomplete="birthplace">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez indiquer votre ville de naissance.') ?>
            </p>
        </div>

        <!-- Code postal -->

        <div class="col-sm-4 wt-page-options-value">
            <input class="form-control" type="number" id="birthpostalcode" name="birthpostalcode" required="required" maxlength="32" value="<?= e($birthpostalcode) ?>" autocomplete="birthpostalcode">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez indiquer le code postal.') ?>
            </p>
        </div>
    </div>

    <!-- Justificatif -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="justificatif">
            <?= I18N::translate('Justificatif') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="file" id="justificatif" name="justificatif" required="required" maxlength="32" value="<?= e($justificatif) ?>" autocomplete="justificatif">
            <p class="small text-muted">
                <?= I18N::translate('Veuillez transmettre un justificatif (carte d\'identité, passeport, permis)') ?>
            </p>
        </div>
    </div>

    <!-- Mot de passe -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="password">
            <?= I18N::translate('Password') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <input class="form-control" type="password" id="password" name="password" placeholder="<?= /* I18N: placeholder text for new-password field */
                                                                                                    I18N::plural('Use at least %s character.', 'Use at least %s characters.', 8, I18N::number(8)) ?>" pattern=".{8,}" required="required" autocomplete="new-password">
            <p class="small text-muted">
                <?= I18N::translate('Passwords must be at least 8 characters long and are case-sensitive, so that “secret” is different from “SECRET”.') ?>
            </p>
        </div>
    </div>

    <!-- Commentaire -->

    <div class="form-group row">
        <label class="col-sm-3 col-form-label wt-page-options-label" for="comment">
            <?= I18N::translate('Comments') ?>
        </label>
        <div class="col-sm-9 wt-page-options-value">
            <textarea class="form-control" id="comment" name="comment" placeholder="<?php /* I18N: placeholder text for registration-comments field */
                                                                                    I18N::translate('Explain why you are requesting an account.') ?>" rows="4" maxlength="255" dir="auto" required="required"><?= e($comments) ?></textarea>
            <p class="small text-muted">
                <?= I18N::translate('Use this field to tell the site administrator why you are requesting an account and how you are related to the genealogy displayed on this site. You can also use this to enter any other comments you may have for the site administrator.') ?>
            </p>
        </div>
    </div>

    <div class="form-group row">
        <div class="col-sm-3 col-form-label wt-page-options-label">
        </div>
        <div class="col-sm-9 wt-page-options-value">
            <button class="btn btn-primary">
                <?= I18N::translate('continue') ?>
            </button>
        </div>
</form>

<?php View::push('javascript') ?>
<script>
    $("#password").hideShowPassword("infer", true);
</script>
<?php View::endpush() ?>